### ISSUE TITLE
Missing CI secrets

### ISSUE THREAD

**Issue by mpetuska** [reduxkotlin/redux-kotlin-compose#1]
The following secrets needs to be added to the repo:
* SIGNING_KEY: raw GPG signing private key
* SIGNING_KEY_ID: GPG signing key ID
* SIGNING_PASSWORD: GPG signing key password (empty secret if none)
* SONATYPE_USERNAME: Nexus publishing username
* SONATYPE_PASSWORD: Nexus publishing password or PAT

**Comment by mpetuska** [comment]
@patjackson52 ping me when done

**Comment by patjackson52** [comment]
@mpetuska these are already added at the org level and should be available with the following names:
![image](https://user-images.githubusercontent.com/537002/183447780-aa5eaec3-a8bd-4e8b-afe8-d5b252543a2e.png)

**Comment by mpetuska** [comment]
Ah, awesome. I'll see if I can make it work.

**Comment by mpetuska** [comment]
Hmm, something is not quite right with the org secrets as they won't let me publish to snapshot repo https://github.com/reduxkotlin/redux-kotlin-compose/runs/7730160325?check_suite_focus=true#step:6:160

Could you double check that gpg key is not expired, matches public key on nexus and nexus credentials have sufficient permissions?

**Comment by junerver** [comment]
awesome! I directly imported the source code into my demo and it works fine with android jetpack-compose. Hope to see it uploaded to maven central soon, I can't wait to use it in future projects.

**Comment by mpetuska** [comment]
FYI: Publish snapshot job was not working in main repo CI for quite some time https://github.com/reduxkotlin/redux-kotlin/actions/workflows/publish_snapshot.yml

**Comment by patjackson52** [comment]
I see.  Not sure what's going on.   I see the 403 error.  Unfortunately I
won't have time to look at this for a few weeks probably.

**Comment by mpetuska** [comment]
@patjackson52 no worries, we all get busy sometimes. Just get to it when you eventually can and until then I'm afraid there's not much else I can do.

**Comment by mpetuska** [comment]
@junerver and others - I've published it to gh packages for now under 0.0.1-SNAPSHOT version https://github.com/reduxkotlin/redux-kotlin-compose/actions/runs/2855527881

**Comment by mpetuska** [comment]
reduxkotlin/redux-kotlin#112

**Comment by mpetuska** [comment]
@patjackson52 I've done some more digging and now I'm sure the issue has something to do with sonatype. 

The credentials are getting propagated properly as seen [here](https://github.com/reduxkotlin/redux-kotlin-compose/actions/runs/3910925649/jobs/6683767942#step:6:84).
The snapshot repo is set correctly as well as seen [here](https://github.com/reduxkotlin/redux-kotlin-compose/blob/master/build-conventions/src/main/kotlin/convention.publishing-nexus.gradle.kts#L10)

I'm not sure why I'm still getting [403](https://github.com/reduxkotlin/redux-kotlin-compose/actions/runs/3910925649/jobs/6683767942#step:6:167)
