### ISSUE TITLE
Could not find org.reduxkotlin:redux-kotlin-compose-jvm

### ISSUE THREAD

**Issue by parkodee** [reduxkotlin/redux-kotlin-compose#6]
I'm trying to use this library for my android jetpack compose app but can't download the library.
I did put `implementation("org.reduxkotlin:redux-kotlin-compose-jvm:_")` in gradle:app but keep getting error
`Cause 1: org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find org.reduxkotlin:redux-kotlin-compose-jvm:_.
Searched in the following locations:
  - https://dl.google.com/dl/android/maven2/org/reduxkotlin/redux-kotlin-compose-jvm/_/redux-kotlin-compose-jvm-_.pom
  - https://repo.maven.apache.org/maven2/org/reduxkotlin/redux-kotlin-compose-jvm/_/redux-kotlin-compose-jvm-_.pom
  - https://jitpack.io/org/reduxkotlin/redux-kotlin-compose-jvm/_/redux-kotlin-compose-jvm-_.pom`

**Comment by parkodee** [comment]
Ok  I replaced it with this `implementation "org.reduxkotlin:redux-kotlin-threadsafe-jvm:0.5.5"`
and now I can work on it.

**Comment by mpetuska** [comment]
FYI this module is only published to gh packages for now so if you want compose integration you need to add gh packages repo. We're having some issues with CI secrets preventing maven central release.
