### ISSUE TITLE
Dispatch from outside of Composable?

### ISSUE THREAD

**Issue by parkodee** [reduxkotlin/redux-kotlin-compose#7]
How can I dispatch action change from outside of composable?
Can't call this from outside composable `val dispatch = rememberDispatcher()`

Any solution ?

**Comment by mpetuska** [comment]
However this gave me some idea for some custom side effect wrappers that would explicitly provide you the dispatcher. Will implement them once We're unblocked with maven central release. 
cc: @patjackson52 what do you think about the idea?

**Comment by mpetuska** [comment]
That's a long way around it, but it works. Hopefully we can publish this artifact to maven central soon so people no longer have to jump through as many hoops.

**Comment by parkodee** [comment]
Yeah a long way but it did the job. hope you publish it to maven soon.
Thankx
